import Link from 'next/link';import {Mail,MapPin,Phone} from 'lucide-react';import {Facebook,Instagram,Youtube} from '@/components/social-icons';import type {FooterGroup,SiteSettings} from '@/lib/api';
const socialIcons:Record<string,typeof Facebook>={Facebook,Instagram,YouTube:Youtube};
const defaultSocial=[{platform:'Facebook',url:'https://www.facebook.com/people/Sps-Mba-Sangamner/pfbid0aYJhnqX6bxJuhHbNrYsKRyCPVzRbBGtVtpzoh4fD4PmLkyoEa4durSixtngaE36yl/'},{platform:'Instagram',url:'https://www.instagram.com/spsmbainstitute/'},{platform:'YouTube',url:'https://www.youtube.com/channel/UC8erfKdVDhEQN4VbIMjb5hg'}];
export function Footer({siteSettings,footerNav}:{siteSettings:SiteSettings|null;footerNav:FooterGroup[]}){
  const address=siteSettings?.address||'Ghulewadi, Pune–Nashik Highway (NH-50), Sangamner – 422605';
  const phone=siteSettings?.phone||'(02425) 223181';const email=siteSettings?.email||'info@spsmba.edu.in';
  const social=(siteSettings?.socialLinks?.length?siteSettings.socialLinks:defaultSocial).filter(s=>socialIcons[s.platform]);
  const footerText=siteSettings?.footerText||`© ${new Date().getFullYear()} SPS MBA Institute. All rights reserved.`;
  return <footer className="bg-navy2 text-white"><div className="mx-auto max-w-[1320px] px-5 pt-20 sm:px-6"><div className="grid gap-12 border-b border-white/10 pb-14 lg:grid-cols-[1.4fr_1fr_1fr_1fr_1fr]"><div><strong className="display block text-2xl font-semibold">M.B.A. Institute</strong><span className="text-xs text-white/50">Sangamner</span><p className="mt-5 max-w-[30ch] text-[12.5px] leading-7 text-white/55">Affiliated to Savitribai Phule Pune University and approved by AICTE, DTE Maharashtra and Government of Maharashtra.</p><div className="mt-6 space-y-3 text-xs text-white/60"><p className="flex gap-2"><MapPin size={15} className="mt-0.5 shrink-0"/>{address}</p><p className="flex gap-2"><Phone size={15}/>{phone}</p><p className="flex gap-2"><Mail size={15}/>{email}</p></div><div className="mt-6 flex gap-2">{social.map(s=>{const Icon=socialIcons[s.platform];return <a key={s.platform} href={s.url} target="_blank" rel="noreferrer" aria-label={s.platform} className="focus-ring grid h-9 w-9 place-items-center border border-white/15 text-white/70 transition hover:border-white/40 hover:text-white"><Icon size={15}/></a>})}</div></div>{footerNav.map(({group,items})=><div key={group}><p className="eyebrow mb-[18px] !text-gold">{group}</p><div className="space-y-[11px] text-[12.5px] text-white/60">{items.map(({label,href})=><Link className="block hover:text-white" href={href} key={href}>{label}</Link>)}</div></div>)}</div><div className="flex items-center justify-between py-[26px] text-[11.5px] text-white/40"><p>{footerText}</p><p className="text-white/65">Spread Knowledge Unto the Last</p></div></div><div className="overflow-hidden leading-[.8]"><span className="display block whitespace-nowrap text-center text-[9rem] font-semibold tracking-tight text-transparent sm:text-[11rem]" style={{WebkitTextStroke:'1px rgba(255,255,255,.14)'}}>SPS MBA Institute</span></div></footer>}
